site_name: TypedRest
site_url: https://typedrest.net/
repo_url: https://github.com/TypedRest/docs
edit_uri: blob/master/docs/

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: octicons/home-24
    repo: fontawesome/brands/github

extra_css: [style.css]
extra_javascript: [matomo.js]

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  # - redirects:
  #    redirect_maps:
  #      old/file.md: new/file.md
  #      some_file.md: http://example.com
